const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let catalog=null;
async function api(url,options={}){const r=await fetch(url,{...options,headers:{...(options.body?{'content-type':'application/json'}:{}),...options.headers}}),d=await r.json();if(!r.ok)throw new Error(d.error||'Fehler');return{...d,httpStatus:r.status};}
function toast(text,error=false){const t=$('#toast');t.textContent=text;t.style.background=error?'#8c211e':'#196a29';t.style.display='block';setTimeout(()=>t.style.display='none',3500)}
$$('nav button').forEach(b=>b.onclick=()=>{$$('nav button').forEach(x=>x.classList.toggle('active',x===b));$$('.page').forEach(p=>p.classList.toggle('active',p.id===b.dataset.page));});
async function status(){const s=await api('/api/status');$('#account').textContent=s.account?`${s.account.displayName} · Steam & VTC verknüpft`:'Steam- und VTC-Anmeldung erforderlich';$('#panel-url').textContent=s.config.panelUrl;$('#telemetry-auto').textContent=s.config.telemetryAutoStart?'Aktiviert':'Deaktiviert';$('#telemetry-status').textContent=s.telemetry.running?'Läuft':s.telemetry.configured?'Bereit, Anmeldung erforderlich':'Token noch nicht eingerichtet';$('#hotkey').textContent=s.config.dispatcherHotkey;const game=$('#play-game').value;$('#games').innerHTML=s.games.filter(g=>g.id===game).map(g=>`<div class="game-row"><b>${g.id==='ets2'?'Euro Truck Simulator 2':'American Truck Simulator'}</b><span>${g.installed?'Installiert':'Nicht gefunden'}</span></div>`).join('');await loadServers();}
async function loadServers(){const game=$('#play-game').value,{servers}=await api(`/api/servers?game=${game}`);$('#servers').innerHTML=servers.length?servers.map(s=>`<div class="game-row"><b>${s.name}</b><span>${s.host}:${s.port}</span></div>`).join(''):'<div class="game-row">Kein passender Server konfiguriert</div>';}
$('#play-game').onchange=status;
$('#steam').onclick=async()=>{try{const{url,userCode}=await api('/api/auth/steam',{method:'POST',body:'{}'});window.open(url,'_blank');toast(`Gerätecode ${userCode} – im Browser mit VTC und Steam bestätigen`);const timer=setInterval(async()=>{try{const result=await api('/api/auth/poll',{method:'POST',body:'{}'});if(result.httpStatus===202)return;clearInterval(timer);toast(`${result.account.displayName} wurde verbunden`);status()}catch(e){clearInterval(timer);toast(e.message,true)}},2000)}catch(e){toast(e.message,true)}};
$('#logout').onclick=async()=>{await api('/api/auth/logout',{method:'POST',body:'{}'});toast('Client abgemeldet');status()};
$('#setup-save').onclick=async()=>{if(!confirm('ETS2 muss geschlossen sein. Jetzt einen separaten VTC-Spielstand als Kopie des neuesten Autosaves anlegen?'))return;try{const result=await api('/api/real-dispatch/setup',{method:'POST',body:JSON.stringify({confirmed:true})});toast(`VTC-Spielstand in Slot ${result.slot} eingerichtet`);status()}catch(e){toast(e.message,true)}};
const f=$('#dispatch-form');
function options(items,label='name'){return items.map(x=>`<option value="${x.id}">${x[label]}</option>`).join('')}
function fillCompanies(cityField,companyField){const city=catalog.cities.find(x=>x.id===f.elements[cityField].value);f.elements[companyField].innerHTML=options(city.companies.map(id=>catalog.companies.find(x=>x.id===id)).filter(Boolean));}
async function compatible(){const q=new URLSearchParams({game:f.elements.game.value,profile:f.elements.mapProfile.value,sourceCompany:f.elements.sourceCompany.value,destinationCompany:f.elements.destinationCompany.value});const d=await api('/api/catalog/compatible?'+q);f.elements.cargo.innerHTML=options(d.cargo);fillTrailers();summary();}
function fillTrailers(){const cargo=catalog.cargo.find(x=>x.id===f.elements.cargo.value);f.elements.trailer.innerHTML=options(catalog.trailers.filter(t=>cargo?.trailers.includes(t.id)));}
function summary(){const text=[f.elements.sourceCity.selectedOptions[0]?.text,f.elements.sourceCompany.selectedOptions[0]?.text,'→',f.elements.destinationCity.selectedOptions[0]?.text,f.elements.destinationCompany.selectedOptions[0]?.text,'·',f.elements.cargo.selectedOptions[0]?.text,'·',f.elements.trailer.selectedOptions[0]?.text].filter(Boolean).join(' ');$('#summary').textContent=text||'Bitte gültige Firmen und eine realistische Frachtkombination wählen.';}
async function loadCatalog(){catalog=await api(`/api/catalog?game=${f.elements.game.value}&profile=${f.elements.mapProfile.value}`);f.elements.sourceCity.innerHTML=options(catalog.cities);f.elements.destinationCity.innerHTML=options([...catalog.cities].reverse());fillCompanies('sourceCity','sourceCompany');fillCompanies('destinationCity','destinationCompany');await compatible();}
f.elements.game.onchange=loadCatalog;f.elements.mapProfile.onchange=loadCatalog;f.elements.sourceCity.onchange=()=>{fillCompanies('sourceCity','sourceCompany');compatible()};f.elements.destinationCity.onchange=()=>{fillCompanies('destinationCity','destinationCompany');compatible()};f.elements.sourceCompany.onchange=compatible;f.elements.destinationCompany.onchange=compatible;f.elements.cargo.onchange=()=>{fillTrailers();summary()};f.elements.trailer.onchange=summary;
f.onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(f));data.navigateOnly=f.elements.navigateOnly.checked;try{const d=await api('/api/dispatch',{method:'POST',body:JSON.stringify(data)});toast('Auftrag realistisch geprüft und reserviert');$('#summary').textContent=`Auftrag ${d.offer.id}: ${d.offer.cargo.name} – ${d.integration.message}`;}catch(err){toast(err.message,true)}};
status();loadCatalog();
