export class MultiplayerClient {
  constructor({panelUrl,accessToken,game,serverId,clientVersion,pluginVersion='not-connected',fetchImpl=fetch}){Object.assign(this,{panelUrl:panelUrl.replace(/\/$/,''),accessToken,game,serverId,clientVersion,pluginVersion,fetchImpl});this.sequence=0;this.session=null;this.players=[];this.lastError=null;this.lastSyncAt=null;}
  headers(){return{authorization:`Bearer ${this.accessToken}`,'content-type':'application/json'};}
  async request(path,payload){const response=await this.fetchImpl(`${this.panelUrl}${path}`,{method:'POST',headers:this.headers(),body:JSON.stringify(payload)}),data=await response.json();if(!response.ok){const error=new Error(data.error||`Multiplayer ${response.status}`);error.status=response.status;throw error;}return data;}
  async join(mapProfile='standard'){const data=await this.request('/api/client/multiplayer/join',{game:this.game,serverId:this.serverId,clientVersion:this.clientVersion,pluginVersion:this.pluginVersion,mapProfile});this.session=data.session;this.sequence=0;this.lastError=null;return data;}
  async heartbeat(state={}){if(!this.session)throw new Error('Multiplayer-Sitzung wurde noch nicht gestartet');try{const data=await this.request('/api/client/multiplayer/heartbeat',{game:this.game,serverId:this.serverId,sequence:++this.sequence,state});this.session=data.self;this.players=data.players;this.lastSyncAt=Date.now();this.lastError=null;return data;}catch(error){this.lastError=error.message;throw error;}}
  async leave(){if(!this.session)return{ok:false};try{return await this.request('/api/client/multiplayer/leave',{game:this.game,serverId:this.serverId});}finally{this.session=null;this.players=[];}}
  snapshot(){return{connected:Boolean(this.session),session:this.session,players:this.players,sequence:this.sequence,lastSyncAt:this.lastSyncAt,lastError:this.lastError};}
}
